"""Clean-action verifier models, datasets, training, and paired collection helpers."""

from .data import (
    CleanChunkExample,
    action_statistics,
    build_clean_chunk_examples,
    candidate_group_split,
    hard_task_keys,
    heldout_task_split,
    known_task_split,
    load_clean_chunk_examples,
    load_candidate_examples,
    select_examples,
    shuffle_actions_within_task,
)
from .model import CleanChunkVerifier, FlattenedVerifier, VerifierOutput
from .collection import (
    SimulatorSnapshot,
    candidate_group_id,
    build_stratified_manifest,
    capture_snapshot,
    collect_candidate_pair,
    collect_initial_pair_fallback,
    postprocess_chunk,
    predict_clean_chunk,
    restore_snapshot,
    validate_snapshot_replay,
)
from .train import (
    TemperatureScaler,
    VerifierTrainConfig,
    calibrate_temperature,
    evaluate_verifier,
    dataset_hash,
    new_verifier_id,
    train_verifier,
    verifier_checkpoint_bytes,
)

__all__ = [
    "CleanChunkExample",
    "action_statistics",
    "CleanChunkVerifier",
    "FlattenedVerifier",
    "TemperatureScaler",
    "VerifierOutput",
    "VerifierTrainConfig",
    "build_clean_chunk_examples",
    "candidate_group_split",
    "calibrate_temperature",
    "evaluate_verifier",
    "dataset_hash",
    "hard_task_keys",
    "heldout_task_split",
    "known_task_split",
    "load_clean_chunk_examples",
    "load_candidate_examples",
    "new_verifier_id",
    "select_examples",
    "shuffle_actions_within_task",
    "train_verifier",
    "verifier_checkpoint_bytes",
    "SimulatorSnapshot",
    "candidate_group_id",
    "build_stratified_manifest",
    "capture_snapshot",
    "collect_candidate_pair",
    "collect_initial_pair_fallback",
    "postprocess_chunk",
    "predict_clean_chunk",
    "restore_snapshot",
    "validate_snapshot_replay",
]
