"""Clean-action verifier models, datasets, training, and paired collection helpers."""

from .data import (
    CleanChunkExample,
    build_clean_chunk_examples,
    candidate_cv_splits,
    candidate_episode_identities,
    exclude_candidate_identities,
    exclude_episode_identities,
    known_task_split,
    load_clean_chunk_examples,
    load_candidate_examples,
    locked_candidate_split,
    prefix_action_statistics,
    select_examples,
    shuffle_candidate_actions_within_group,
    validate_candidate_groups,
)
from .model import (
    CompactAdvantageVerifier,
    VerifierOutput,
)
from .collection import (
    candidate_group_id,
    build_stratified_manifest,
    build_targeted_manifests,
    build_seeded_pro_manifest,
    collection_manifest_hash,
    collect_replay_candidate_group,
    postprocess_chunk,
    predict_clean_chunk,
)
from .train import (
    AdvantageTrainConfig,
    evaluate_candidate_ranker,
    candidate_rank_records,
    dataset_hash,
    new_verifier_id,
    train_advantage,
    pretrain_value,
    paired_candidate_comparison,
    summarize_candidate_records,
    verifier_registration_eligibility,
    verifier_checkpoint_bytes,
)

__all__ = [
    "CleanChunkExample",
    "CompactAdvantageVerifier",
    "VerifierOutput",
    "AdvantageTrainConfig",
    "build_clean_chunk_examples",
    "candidate_cv_splits",
    "candidate_episode_identities",
    "evaluate_candidate_ranker",
    "candidate_rank_records",
    "exclude_candidate_identities",
    "exclude_episode_identities",
    "dataset_hash",
    "known_task_split",
    "load_clean_chunk_examples",
    "load_candidate_examples",
    "locked_candidate_split",
    "new_verifier_id",
    "select_examples",
    "prefix_action_statistics",
    "shuffle_candidate_actions_within_group",
    "validate_candidate_groups",
    "train_advantage",
    "pretrain_value",
    "paired_candidate_comparison",
    "summarize_candidate_records",
    "verifier_registration_eligibility",
    "verifier_checkpoint_bytes",
    "candidate_group_id",
    "build_stratified_manifest",
    "build_targeted_manifests",
    "build_seeded_pro_manifest",
    "collection_manifest_hash",
    "collect_replay_candidate_group",
    "postprocess_chunk",
    "predict_clean_chunk",
]
